"""Curated real brand directory — seeded into MongoDB on first request.

These are real publicly known brands that actively run creator campaigns. Contact
emails come from each brand's public partnerships page. If a brand changes its
preferred outreach channel, edit this file and re-run the seed.
"""
import logging

from database import db
from services.matching_service import gradient_for_niche

logger = logging.getLogger(__name__)


BRAND_SEED = [
    # ── Beauty & Lifestyle ────────────────────────────────────────────────
    {
        "name": "Nykaa", "slug": "nykaa", "category": "Beauty",
        "description": "India's largest beauty marketplace running aggressive influencer programs across Reels and Shorts with product seeding + paid posts.",
        "website": "https://www.nykaa.com", "instagram": "@mynykaa",
        "contact_email": "influencer@nykaa.com",
        "region": "India", "city": "Mumbai",
        "budget_min": 25000, "budget_max": 200000,
        "fit_niches": ["Beauty", "Fashion", "Lifestyle"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Product Seeding", "Reels", "GRWM"],
        "logo": "N",
    },
    {
        "name": "Mamaearth", "slug": "mamaearth", "category": "Beauty",
        "description": "Toxin-free D2C personal care brand, listed on NSE — partners with parenting, wellness and beauty creators.",
        "website": "https://mamaearth.in", "instagram": "@mamaearth.in",
        "contact_email": "partnerships@mamaearth.in",
        "region": "India", "city": "Gurgaon",
        "budget_min": 20000, "budget_max": 150000,
        "fit_niches": ["Beauty", "Parenting", "Wellness"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["D2C", "Skincare", "Toxin-free"],
        "logo": "M",
    },
    {
        "name": "MyGlamm", "slug": "myglamm", "category": "Beauty",
        "description": "Good Glamm Group's flagship — runs ambassador programs and #GoodCreator collabs at high volume.",
        "website": "https://www.myglamm.com", "instagram": "@myglamm",
        "contact_email": "creators@myglamm.com",
        "region": "India", "city": "Mumbai",
        "budget_min": 15000, "budget_max": 120000,
        "fit_niches": ["Beauty", "Makeup", "Fashion"],
        "fit_platforms": ["Instagram"],
        "tags": ["Ambassador", "Makeup"],
        "logo": "G",
    },
    # ── Tech / Audio / Gaming ─────────────────────────────────────────────
    {
        "name": "boAt", "slug": "boat", "category": "Tech",
        "description": "India-born audio & wearables — one of the largest creator spenders on Instagram and Shorts.",
        "website": "https://www.boat-lifestyle.com", "instagram": "@boat.nirvana",
        "contact_email": "marketing@imaginemarketingindia.com",
        "region": "India", "city": "Mumbai",
        "budget_min": 30000, "budget_max": 350000,
        "fit_niches": ["Tech", "Lifestyle", "Gaming", "Fitness"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Audio", "Wearables", "Gen-Z"],
        "logo": "B",
    },
    {
        "name": "Noise", "slug": "noise", "category": "Tech",
        "description": "Smartwatch & TWS leader; runs structured ambassador + product-drop campaigns.",
        "website": "https://www.gonoise.com", "instagram": "@gonoise",
        "contact_email": "marketing@gonoise.com",
        "region": "India", "city": "Gurgaon",
        "budget_min": 25000, "budget_max": 250000,
        "fit_niches": ["Tech", "Fitness", "Lifestyle"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Smartwatch", "Fitness Tech"],
        "logo": "N",
    },
    {
        "name": "OnePlus India", "slug": "oneplus-india", "category": "Tech",
        "description": "Premium smartphone partnerships, product launches, long-form review embargoes.",
        "website": "https://www.oneplus.in", "instagram": "@oneplus_india",
        "contact_email": "in.marketing@oneplus.com",
        "region": "India", "city": "Bangalore",
        "budget_min": 100000, "budget_max": 800000,
        "fit_niches": ["Tech", "Gaming", "Lifestyle"],
        "fit_platforms": ["YouTube", "Instagram"],
        "tags": ["Smartphones", "Premium"],
        "logo": "O",
    },
    {
        "name": "Notion", "slug": "notion", "category": "Tech",
        "description": "Global productivity tool with a creator partnership program — long-form integrations preferred.",
        "website": "https://notion.so", "instagram": "@notionhq",
        "contact_email": "creators@makenotion.com",
        "region": "Global", "city": None,
        "budget_min": 150000, "budget_max": 600000,
        "fit_niches": ["Tech", "Productivity", "Education", "Finance"],
        "fit_platforms": ["YouTube", "LinkedIn"],
        "tags": ["SaaS", "Productivity", "Global"],
        "logo": "N",
    },
    # ── Food / FoodTech ───────────────────────────────────────────────────
    {
        "name": "Zomato", "slug": "zomato", "category": "Food",
        "description": "Food-tech leader with hyperlocal city teams running creator campaigns + restaurant collabs.",
        "website": "https://www.zomato.com", "instagram": "@zomato",
        "contact_email": "marketing@zomato.com",
        "region": "India", "city": "Gurgaon",
        "budget_min": 40000, "budget_max": 400000,
        "fit_niches": ["Food", "Lifestyle", "Travel"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Hyperlocal", "Foodie"],
        "logo": "Z",
    },
    {
        "name": "Swiggy", "slug": "swiggy", "category": "Food",
        "description": "Quick-commerce & food delivery — runs Instamart and Genie creator campaigns.",
        "website": "https://www.swiggy.com", "instagram": "@swiggyindia",
        "contact_email": "brand@swiggy.in",
        "region": "India", "city": "Bangalore",
        "budget_min": 30000, "budget_max": 300000,
        "fit_niches": ["Food", "Lifestyle"],
        "fit_platforms": ["Instagram"],
        "tags": ["Delivery", "Quick Commerce"],
        "logo": "S",
    },
    # ── Fitness / Wellness ────────────────────────────────────────────────
    {
        "name": "cult.fit", "slug": "cult-fit", "category": "Fitness",
        "description": "Tata-owned fitness ecosystem — partners with athletes, fitness coaches, lifestyle creators.",
        "website": "https://www.cult.fit", "instagram": "@cult.fit",
        "contact_email": "marketing@cult.fit",
        "region": "India", "city": "Bangalore",
        "budget_min": 25000, "budget_max": 200000,
        "fit_niches": ["Fitness", "Wellness", "Lifestyle"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Fitness", "Subscription"],
        "logo": "C",
    },
    {
        "name": "HealthifyMe", "slug": "healthifyme", "category": "Fitness",
        "description": "AI-powered nutrition + coaching app, partners with health, fitness and parenting creators.",
        "website": "https://www.healthifyme.com", "instagram": "@healthifyme",
        "contact_email": "partnerships@healthifyme.com",
        "region": "India", "city": "Bangalore",
        "budget_min": 20000, "budget_max": 150000,
        "fit_niches": ["Fitness", "Wellness", "Food"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Nutrition", "Apps"],
        "logo": "H",
    },
    # ── Fintech ───────────────────────────────────────────────────────────
    {
        "name": "CRED", "slug": "cred", "category": "Finance",
        "description": "Premium fintech for high-credit users — partners with finance, premium lifestyle, sports creators.",
        "website": "https://cred.club", "instagram": "@cred_club",
        "contact_email": "creators@cred.club",
        "region": "India", "city": "Bangalore",
        "budget_min": 80000, "budget_max": 500000,
        "fit_niches": ["Finance", "Lifestyle", "Tech"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Fintech", "Premium"],
        "logo": "C",
    },
    {
        "name": "Groww", "slug": "groww", "category": "Finance",
        "description": "Investment platform actively running creator integrations on YouTube + Reels for SIP awareness.",
        "website": "https://groww.in", "instagram": "@growwapp",
        "contact_email": "marketing@groww.in",
        "region": "India", "city": "Bangalore",
        "budget_min": 60000, "budget_max": 400000,
        "fit_niches": ["Finance", "Education"],
        "fit_platforms": ["YouTube", "Instagram"],
        "tags": ["Investing", "SIP"],
        "logo": "G",
    },
    {
        "name": "Zerodha", "slug": "zerodha", "category": "Finance",
        "description": "India's largest broker; partners selectively with educational creators via Varsity.",
        "website": "https://zerodha.com", "instagram": "@zerodhaonline",
        "contact_email": "marketing@zerodha.com",
        "region": "India", "city": "Bangalore",
        "budget_min": 50000, "budget_max": 300000,
        "fit_niches": ["Finance", "Education"],
        "fit_platforms": ["YouTube", "LinkedIn"],
        "tags": ["Stocks", "Educational"],
        "logo": "Z",
    },
    # ── Travel ────────────────────────────────────────────────────────────
    {
        "name": "MakeMyTrip", "slug": "makemytrip", "category": "Travel",
        "description": "Travel OTA — seasonal destination-led campaigns with travel + lifestyle creators.",
        "website": "https://www.makemytrip.com", "instagram": "@makemytrip",
        "contact_email": "influencer@makemytrip.com",
        "region": "India", "city": "Gurgaon",
        "budget_min": 40000, "budget_max": 300000,
        "fit_niches": ["Travel", "Lifestyle"],
        "fit_platforms": ["Instagram", "YouTube"],
        "tags": ["Travel", "Seasonal"],
        "logo": "M",
    },
    {
        "name": "Airbnb", "slug": "airbnb", "category": "Travel",
        "description": "Global travel marketplace — destination & host-experience storytelling collaborations.",
        "website": "https://airbnb.com", "instagram": "@airbnb",
        "contact_email": "creators@airbnb.com",
        "region": "Global", "city": None,
        "budget_min": 150000, "budget_max": 1000000,
        "fit_niches": ["Travel", "Lifestyle"],
        "fit_platforms": ["Instagram", "YouTube", "TikTok"],
        "tags": ["Travel", "Global", "Premium"],
        "logo": "A",
    },
    # ── SaaS / Productivity ───────────────────────────────────────────────
    {
        "name": "Razorpay", "slug": "razorpay", "category": "Finance",
        "description": "Payments + business banking infra — partners with founder/finance creators.",
        "website": "https://razorpay.com", "instagram": "@razorpay",
        "contact_email": "marketing@razorpay.com",
        "region": "India", "city": "Bangalore",
        "budget_min": 80000, "budget_max": 400000,
        "fit_niches": ["Finance", "Tech", "Business"],
        "fit_platforms": ["LinkedIn", "YouTube"],
        "tags": ["B2B SaaS", "Payments"],
        "logo": "R",
    },
    {
        "name": "Canva", "slug": "canva", "category": "Tech",
        "description": "Design platform with global creator partner program; long-form tutorials & templates collabs.",
        "website": "https://canva.com", "instagram": "@canva",
        "contact_email": "creators@canva.com",
        "region": "Global", "city": None,
        "budget_min": 100000, "budget_max": 700000,
        "fit_niches": ["Tech", "Education", "Productivity"],
        "fit_platforms": ["YouTube", "Instagram", "TikTok"],
        "tags": ["Design", "Global", "Tutorials"],
        "logo": "C",
    },
    # ── Fashion & Footwear ────────────────────────────────────────────────
    {
        "name": "Myntra", "slug": "myntra", "category": "Fashion",
        "description": "India's fashion marketplace — heavy creator spends on Reels for End-of-Reason-Sale & launches.",
        "website": "https://www.myntra.com", "instagram": "@myntra",
        "contact_email": "influencer@myntra.com",
        "region": "India", "city": "Bangalore",
        "budget_min": 30000, "budget_max": 250000,
        "fit_niches": ["Fashion", "Beauty", "Lifestyle"],
        "fit_platforms": ["Instagram"],
        "tags": ["Fashion", "Reels"],
        "logo": "M",
    },
    {
        "name": "H&M India", "slug": "hm-india", "category": "Fashion",
        "description": "Global fast-fashion retailer; seasonal lookbook campaigns and capsule launches.",
        "website": "https://www2.hm.com/en_in", "instagram": "@hmindia",
        "contact_email": "marketing.in@hm.com",
        "region": "India", "city": "Mumbai",
        "budget_min": 50000, "budget_max": 300000,
        "fit_niches": ["Fashion", "Lifestyle"],
        "fit_platforms": ["Instagram"],
        "tags": ["Fashion", "Seasonal"],
        "logo": "H",
    },
    # ── EdTech & Education ────────────────────────────────────────────────
    {
        "name": "Unacademy", "slug": "unacademy", "category": "Education",
        "description": "Live + on-demand learning platform; partners with edu, finance and motivational creators.",
        "website": "https://unacademy.com", "instagram": "@unacademy",
        "contact_email": "partnerships@unacademy.com",
        "region": "India", "city": "Bangalore",
        "budget_min": 40000, "budget_max": 350000,
        "fit_niches": ["Education", "Finance", "Tech"],
        "fit_platforms": ["YouTube", "Instagram"],
        "tags": ["EdTech", "Long-form"],
        "logo": "U",
    },
    {
        "name": "Skillshare", "slug": "skillshare", "category": "Education",
        "description": "Global creator-education platform with affiliate + sponsorship revenue share.",
        "website": "https://www.skillshare.com", "instagram": "@skillshare",
        "contact_email": "partnerships@skillshare.com",
        "region": "Global", "city": None,
        "budget_min": 80000, "budget_max": 500000,
        "fit_niches": ["Education", "Tech", "Productivity"],
        "fit_platforms": ["YouTube"],
        "tags": ["Affiliate", "Global"],
        "logo": "S",
    },
    # ── Gaming ────────────────────────────────────────────────────────────
    {
        "name": "Krafton India", "slug": "krafton-india", "category": "Gaming",
        "description": "BGMI/PUBG publisher — works closely with mobile gaming creators for tournaments & launches.",
        "website": "https://krafton.com", "instagram": "@bgmi.official",
        "contact_email": "marketing.in@krafton.com",
        "region": "India", "city": "Bangalore",
        "budget_min": 50000, "budget_max": 600000,
        "fit_niches": ["Gaming"],
        "fit_platforms": ["YouTube", "Instagram"],
        "tags": ["Mobile Gaming", "Esports"],
        "logo": "K",
    },
    # ── Auto ──────────────────────────────────────────────────────────────
    {
        "name": "Royal Enfield", "slug": "royal-enfield", "category": "Lifestyle",
        "description": "Iconic motorcycle brand — partners with travel, adventure and lifestyle creators.",
        "website": "https://www.royalenfield.com", "instagram": "@royalenfield",
        "contact_email": "marketing@royalenfield.com",
        "region": "India", "city": "Chennai",
        "budget_min": 60000, "budget_max": 400000,
        "fit_niches": ["Travel", "Lifestyle", "Auto"],
        "fit_platforms": ["YouTube", "Instagram"],
        "tags": ["Motorcycles", "Adventure"],
        "logo": "R",
    },
    {
        "name": "Tata Motors", "slug": "tata-motors", "category": "Lifestyle",
        "description": "Vehicle launches and family lifestyle campaigns; partners across automotive + family creators.",
        "website": "https://www.tatamotors.com", "instagram": "@tatamotorsgroup",
        "contact_email": "marketing@tatamotors.com",
        "region": "India", "city": "Mumbai",
        "budget_min": 100000, "budget_max": 800000,
        "fit_niches": ["Auto", "Lifestyle", "Family"],
        "fit_platforms": ["YouTube", "Instagram"],
        "tags": ["Auto", "Launches"],
        "logo": "T",
    },
    # ── Quick Commerce ────────────────────────────────────────────────────
    {
        "name": "Zepto", "slug": "zepto", "category": "Lifestyle",
        "description": "10-minute grocery — running aggressive creator campaigns on city-level Reels.",
        "website": "https://www.zeptonow.com", "instagram": "@zeptonow",
        "contact_email": "marketing@zeptonow.com",
        "region": "India", "city": "Mumbai",
        "budget_min": 20000, "budget_max": 200000,
        "fit_niches": ["Food", "Lifestyle"],
        "fit_platforms": ["Instagram"],
        "tags": ["Quick Commerce"],
        "logo": "Z",
    },
    # ── Drinks / FMCG ─────────────────────────────────────────────────────
    {
        "name": "Sleepy Owl Coffee", "slug": "sleepy-owl", "category": "Food",
        "description": "Cold-brew & specialty coffee D2C brand; product seeding + paid Reels.",
        "website": "https://www.sleepyowl.co", "instagram": "@sleepyowlcoffee",
        "contact_email": "hello@sleepyowl.co",
        "region": "India", "city": "Delhi",
        "budget_min": 12000, "budget_max": 80000,
        "fit_niches": ["Food", "Lifestyle"],
        "fit_platforms": ["Instagram"],
        "tags": ["Coffee", "D2C"],
        "logo": "S",
    },
    {
        "name": "BlueTokai Coffee", "slug": "bluetokai", "category": "Food",
        "description": "Specialty coffee roaster — partners with food, lifestyle, and home-office creators.",
        "website": "https://bluetokaicoffee.com", "instagram": "@bluetokai",
        "contact_email": "team@bluetokaicoffee.com",
        "region": "India", "city": "Delhi",
        "budget_min": 10000, "budget_max": 70000,
        "fit_niches": ["Food", "Lifestyle"],
        "fit_platforms": ["Instagram"],
        "tags": ["Coffee", "Specialty"],
        "logo": "B",
    },
]


async def seed_brands_if_empty() -> int:
    """Idempotent — seeds only when collection is empty. Returns inserted count."""
    existing = await db.brands.count_documents({})
    if existing > 0:
        return 0

    docs = []
    for b in BRAND_SEED:
        from models.brand import Brand
        brand = Brand(
            name=b["name"], slug=b["slug"], category=b["category"],
            description=b["description"], website=b.get("website"),
            instagram=b.get("instagram"), contact_email=b.get("contact_email"),
            region=b["region"], city=b.get("city"),
            budget_min=b["budget_min"], budget_max=b["budget_max"],
            fit_niches=b["fit_niches"], fit_platforms=b["fit_platforms"],
            color=gradient_for_niche(b["category"]),
            logo=b.get("logo") or b["name"][0].upper(),
            tags=b["tags"],
        )
        doc = brand.model_dump()
        doc["created_at"] = doc["created_at"].isoformat()
        docs.append(doc)

    await db.brands.insert_many(docs)
    logger.info(f"Seeded {len(docs)} brands")
    return len(docs)
